export {default as logo} from "./logo.svg"
export {default as amr} from "./amr.png"

// export {default as project1} from "./project1.png"
// export {default as project2} from "./project2.png"
// export {default as project3} from "./project3.png"
// export {default as project4} from "./project4.png"
export {default as dall} from "./DALL·E 2.jpg"
export {default as note} from "./note.png"
export {default as blog} from "./Capture3.jpg"
export {default as zekr} from "./dekr2.jpg"
export {default as ecom} from "./ecpommers.jpg"
export {default as proto} from "./proto.jpg"
export {default as elon} from "./elonwebp.webp"
export {default as hubber} from "./download.webp"
export {default as grace} from "./grace.webp"
export {default as gates } from "./billgates.webp"
export {default as alun } from "./alun.webp"
export {default as steve} from "./stev.webp"
// export {default as } from "./"